services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  app:
    build: .
    container_name: register-leads-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"
    depends_on:
      - mysql_db
    volumes:
      - .:/app


volumes:
  db_data:
