@startuml
actor User
boundary Interfaz
control ControladorRegistrarLead

User -> Interfaz: optNewLead(data)
Interfaz -> ControladorRegistrarLead: newLead(data)
ControladorRegistrarLead -> ControladorRegistrarLead: validarDatos()
ControladorRegistrarLead -> ControladorRegistrarLead: yaExiste()

create entity Lead
ControladorRegistrarLead -> Lead: new(datos)

create entity Cursado
Lead -> Cursado: new()

loop
    create entity DetalleCursado
    Cursado -> DetalleCursado: agregarNuevoDetalle()

    entity Carrera
    DetalleCursado -> Carrera: addCarrera()
    entity Materia
    loop
        DetalleCursado -> Materia: getMateriaName()
    end

    DetalleCursado -> Cursado: return(DetalleCursado)
end
Interfaz -> User: mostrarMsjSuccess()
Interfaz -> User: mostrarLeadId()
@enduml